version: "3.2"

services:
  database:
    image: mysql:8.0
    container_name: database
    volumes:
      - db_data:/var/lib/mysql-files
    restart: always
    ports:
      - "3306:3306"
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    environment:
     - MYSQL_ROOT_PASSWORD=1234
     - MYSQL_DATABASE=app_db


volumes:
  db_data: